# This is a basic workflow that is manually triggered
name: CI

# Controls when the workflow will run

on:
  #schedule:
  #  - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    permissions: write-all  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main
    - name: ConvertModel
      run: |
        cp -r main/* .
        git clone https://github.com/hzwer/Practical-RIFE
        rm -rf Practical-RIFE/requirements.txt
        cp -r Practical-RIFE/* .
        sudo apt install libprotobuf17 -y
        pip install onnxsim onnxconverter_common torch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 

        wget https://raw.githubusercontent.com/TNTwise/Rife-NCNN-Model-Comparisons/c053eaf9b51fa07467954d4d8ed1cf752b1fd68b/0.png && wget https://raw.githubusercontent.com/TNTwise/Rife-NCNN-Model-Comparisons/c053eaf9b51fa07467954d4d8ed1cf752b1fd68b/2.png
        pip install -r requirements.txt

        python3 modify_train_log.py
        mv train_log/ train_log_backup/
        mv train_log_export/ train_log/
        python3 inference_img.py  --img 0.png 2.png --exp 1 
        mv train_log/ train_log_export/ 
        mv train_log_backup/ train_log/
        chmod +x ncnnoptimize
        chmod +x onnx2ncnn
        onnxsim rife.onnx rife-sim.onnx
        ./onnx2ncnn  rife-sim.onnx flownet-sim.param flownet-sim.bin
        ./ncnnoptimize flownet-sim.param flownet-sim.bin flownet.param flownet.bin 65536 #the 65535 converts it to fp16
        python3 fix_param_file.py

   
    

    - name: Save extracted files as artifact
      uses: actions/upload-artifact@v3
      with:
          name: model
          path: |
            flownet.bin
            flownet.param

    
